import type { ComponentInstance } from '@/types'
import { generateReactCode, generateHTMLCode } from './reactExport'
import { generateVueCode } from './vueExport'
import { generateSvelteCode } from './svelteExport'

export type ExportFormat = 'react' | 'html' | 'react-ts' | 'vue' | 'svelte'

export interface ExportResult {
  format: ExportFormat
  code: string
  files: { name: string; content: string }[]
  language: string
}

export function exportProject(
  nodes: Record<string, ComponentInstance>,
  rootIds: string[],
  format: ExportFormat = 'react',
): ExportResult {
  switch (format) {
    case 'react':
    case 'react-ts': {
      const code = generateReactCode(nodes, rootIds)
      return {
        format,
        code,
        files: [
          { name: 'Page.tsx', content: code },
          { name: 'styles.css', content: '/* Generated by UIForge */\n/* Add your custom styles here */' },
        ],
        language: 'tsx',
      }
    }
    case 'html': {
      const code = generateHTMLCode(nodes, rootIds)
      return {
        format,
        code,
        files: [{ name: 'index.html', content: code }],
        language: 'html',
      }
    }
    case 'vue': {
      const code = generateVueCode(nodes, rootIds)
      return {
        format,
        code,
        files: [{ name: 'Page.vue', content: code }],
        language: 'html',
      }
    }
    case 'svelte': {
      const code = generateSvelteCode(nodes, rootIds)
      return {
        format,
        code,
        files: [{ name: 'Page.svelte', content: code }],
        language: 'html',
      }
    }
  }
}
